### ISSUE TITLE
動歩行の実装

### ISSUE THREAD

**Issue by Yusuke-Yamasaki-555** [open-rdc/ROS2_Walking_Pattern_Generator#6]

**Comment by Yusuke-Yamasaki-555** [comment]
静歩行は一旦白紙。逆運動学->動歩行を考える。

**Comment by Yusuke-Yamasaki-555** [comment]
本格的な動歩行の実装に向けて、開発を勧めていく。

[ROBOTIS OP2の重量・足裏から腰までの高さ。](http://en.robotis.com/img/sub/pruduct_img_OP2_07.png)
・重量：3.0[kg]
・腰の高さ：219.5[mm]

これを元に、軌道エネルギーの式を立てて、歩行パラメータを構築する。そしたら、歩行パターン生成のための実装を進めていく。

実装方法は、はじめは動けば良いので、WebotsRobotHandlerに直接実装する。step()でリアルタイムに生成するのではなく、init()で歩行パターンを全て計算しておき、step()で順次パターンを読んで動かす方法を取る。

**Comment by Yusuke-Yamasaki-555** [comment]
理論のそれっぽいコードは書けたので、まずは重心軌道がちゃんと生成されているか確認している。
まだ上手くできていない。

本の数式と、本と先生のコードのアルゴリズムを参考に構築中。コードとアルゴリズムに関しては、コピペはしてないし、写してもいない、見ながらもやっていないので、セーフ。数式はほぼ写しているが、コレは別問題。

**Comment by Yusuke-Yamasaki-555** [comment]
プロットしてみたが、やっぱしうまくいっていない。用修正。


![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/ccbd78ba-ba43-4898-8ca1-51c336bed77a)

**Comment by Yusuke-Yamasaki-555** [comment]
単に、着地位置がだめかも？特にはじめの２，３歩。計算がおかしいのだろうな。

**Comment by Yusuke-Yamasaki-555** [comment]
![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/02215027-6159-4d39-8eb0-2f02ef3b3c2a)

ce5e28362d617b446130d7ba85d70e98d2f4a733

記録

**Comment by Yusuke-Yamasaki-555** [comment]
改めて考え直したら、色々と腑に落とせた。アルゴリズムは理解できたような気がする。コレならちゃんとしたプログラムが書けそう。
上で挙げたグラフとかは、やっぱ理論の実装が色々と間違ってた。

基準座標のx軸が右足の足裏中心点を通るのは少し気持ち悪いが、IKを解くときやグラフに直すときに、y軸要素の値を調整すれば良いか。

![image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/ac09b7a4-5a70-4696-8cdc-7d792923ca71)

**Comment by Yusuke-Yamasaki-555** [comment]
着地位置の修正をしないとこんな感じ。なんかできてそうなできてなさそうな。

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/0b46103d-c22b-4652-8659-1a168226c387)

**Comment by Yusuke-Yamasaki-555** [comment]
それっぽいグラフは得られた。足踏みの重心軌道はうまく得られている気がする。ただ、初めの1,2歩は思惑通りにいっていない。

まだ釈然としないというか、負に落とせているとは思うが、あまりうまくいかんなぁ。XとYでそれほど大きな違いは無いはずなんだが。

e29a13fcc38a6a5be8e77d8a4dbc7a1b60d9d75b

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/546b93e3-5ebd-44b1-96fa-f4369e8a22a8)

**Comment by Yusuke-Yamasaki-555** [comment]
X軸方向の運動も入れてみた。んーそれっぽい。
教科書のやつとY軸が結構違うのは、脚の長さや着地位置が違うからかな。

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/1e4f327f-d24b-43bf-a63b-04cdca46086c)

やっぱ、X軸を考える場合は歩行パラメータをちゃんと定めないと、ありえない値が得られちゃうな。

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/6506f9b8-821d-470a-99ff-65cdb4302e3a)

Y軸のものであっても、歩行パラメータを変えてやったり最適化問題の重みパラメータを変えてやれば、もっといい感じの結果が得られそうだなと思った。

**Comment by Yusuke-Yamasaki-555** [comment]
いやー、単位が違いました。

着地位置を[m]で扱っていたのに、脚の長さを[mm]で扱っていました。

**Comment by Yusuke-Yamasaki-555** [comment]
?????



![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/03be2ebb-5ce5-4ef6-921e-dd0109414a56)

**Comment by Yusuke-Yamasaki-555** [comment]
教科書のパラメータでPlotしてみた。ちゃんとしたものが出ている。

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/e1c7e34c-1020-4fa8-99e7-251bd1c8d4b8)

　まず、初期重心位置がだめだった。初期支持脚着地位置と初期重心位置を一致させなければ、教科書の方法はだめな気がする。
　他は特に問題がなかったので、あとはパラメータの設定次第。

**Comment by Yusuke-Yamasaki-555** [comment]
初期姿勢は直立が良いので、もう１ステップ増やして初期着地位置を直立状態の重心位置としてやればいい感じになるかもしれない。

**Comment by Yusuke-Yamasaki-555** [comment]
倒立伸子なんだし、初期支持脚位置と初期重心位置がズレてたら、そら豪快に倒れるわな。

2足歩行ロボットじゃなくて倒立伸子であることを意識しなきゃダメ。

だから、最初は重心と支持脚が同じ位置にするために、直立状態と同じ支持脚位置を初期として、やるべきなんじゃないか？

**Comment by Yusuke-Yamasaki-555** [comment]
いや、やっぱ上手くいっていないな。初めの1、2歩がやっぱダメだな

**Comment by Yusuke-Yamasaki-555** [comment]
やっぱ１，２歩目がだめだった。初期着地位置に対して、着地位置修正を掛けていなかったのが原因だった。

これでちゃんと教科書の動きが再現できたはず。

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/25144a2b-e430-45c3-b937-aa1cff1d7562)

**Comment by Yusuke-Yamasaki-555** [comment]
足踏みで速度もプロットしてみたVersion。めっちゃきれい。最高。



![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/a5e76c8a-81ac-4744-b219-093d456b954a)

**Comment by Yusuke-Yamasaki-555** [comment]
前進に速度もプロットしてみたVersion。本当は別のグラフに分けたほうが良いが、ひとまずこれで。

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/661e981f-30c8-4531-8a24-4d71f569ac4e)

**Comment by Yusuke-Yamasaki-555** [comment]
開発環境に合わせて、足踏みの歩行パラメータにしてみたVersion。あとはパラメータ調整して、遊脚軌道（正弦波）考えて、IK解いて、ロボットに適用すればOKかな。



![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/0c8f2759-18c7-4e25-a943-148aad79e4b8)

**Comment by Yusuke-Yamasaki-555** [comment]
初期重心位置を直立状態に合わせたVersion。修正着地位置が重心位置と一致したので、これは実現不可能ですね。

歩き始めはやっぱ、こちらから右脚の片足支持まで持っていってから歩き始めたほうがいいのか？

![Image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/ce2a35e7-79d7-4dba-8a8c-36c3502c15b4)

**Comment by Yusuke-Yamasaki-555** [comment]
静歩行の実装の時に使った方法を参考に実装するのも良いだろう。

**Comment by Yusuke-Yamasaki-555** [comment]
初期重心位置は別に直立状態で良いか。着地位置もそれに合わせよう。直立状態は両脚支持なんだから、その時の着地位置は実質的に体の中心にある。

**Comment by Yusuke-Yamasaki-555** [comment]
最適化問題の重みを変えてみた。１、１０、１００と変えてみたが、ほとんど変化なし。グラフにはほとんど現れていないので、省略。

まあもともと、着地位置の修正が見られなかったので、重みを変えてもほとんど変化が無いのは自明の理、的な。

なので、変えるとしたら着地位置ではあるのだが、今の着地位置は足を上下にしか動かすだけになっている。これ以上内側に設定したら、左右の足が切替時に干渉しかねないので、これで行くしかないかなぁと思っている。

**Comment by Yusuke-Yamasaki-555** [comment]
次にやること。

：遊脚軌道の生成と、実装方法の検討

**Comment by Yusuke-Yamasaki-555** [comment]
歩行パラメータを生成して実装するところまでを、ひとまずやってみた。

が、やはりそううまくは動かなかった。

以下、Webots側で出力されたエラーの一部
```
DLegLowerR HingeJoint > Solid > DEF DAnkleR HingeJoint > RotationalMotor: too low requested position: -2.72454 < -1.24
WARNING: DEF ROBOTIS_OP2 RobotisOp2 (PROTO) > DEF DPelvYR HingeJoint > Solid > DEF DPelvR HingeJoint > Solid > DEF DLegUpperR HingeJoint > Solid > DEF DLegLowerR HingeJoint > Solid > DEF DAnkleR HingeJoint > Solid > DEF DFootR HingeJoint > RotationalMotor: too low requested position: -3.0882 < -0.68
WARNING: DEF ROBOTIS_OP2 RobotisOp2 (PROTO) > DEF DPelvYL HingeJoint > RotationalMotor: too big requested position: 3.14159 > 2.5
WARNING: DEF ROBOTIS_OP2 RobotisOp2 (PROTO) > DEF DPelvYL HingeJoint > Solid > DEF DPelvL HingeJoint > Solid > DEF DLegUpperL HingeJoint > Solid > DEF DLegLowerL HingeJoint > Solid > DEF DAnkleL HingeJoint > RotationalMotor: too big requested position: 2.80885 > 1.22
```

**Comment by Yusuke-Yamasaki-555** [comment]
歩行パラメータで生成した指定関節角度がだめ。指定範囲外の値になっている。

以降、原因を特定して、バグを修正する。

**Comment by Yusuke-Yamasaki-555** [comment]
* PelvYL: 左脚腰関節Z軸: 足踏み・直進では使わない。3.14159（つまり180度）しか与えていない。つまりIKの問題？
* AnkleL: 左脚足首Y軸
* FootL: 左脚足首X軸: この２つはよくわからん。どっちにしろIKが悪さしてそう。

**Comment by Yusuke-Yamasaki-555** [comment]
遊脚軌道は正弦波を考えているわけだが、その適用方法は、重心位置のZ軸から正弦波の値をそのまま引いてやった重心位置を、遊脚がIKを解くときに使えは、遊脚軌道が達成できると考える。

IKは各脚の床面との設置点を基準点（0, 0, 0）としているので、重心位置から引いてやる方法しかないとは思うが。

以下、重心位置をプロットした３次元グラフ。単にプロットしただけだから分かりづらい。
![WPG_log_v10](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/9205a433-c102-46df-8d27-d8da84e4eb06)

このグラフ的に、ちゃんと重心位置から遊脚軌道が引かれていて、支持脚切替タイミングで元の重心位置と一致しているので、OKだと思われ。初めのX軸0~0.8では遊脚が発生しないので無視で。（両脚支持期間はまだ設けてない。）

**Comment by Yusuke-Yamasaki-555** [comment]
やっぱIKか？

**Comment by Yusuke-Yamasaki-555** [comment]
それより、他の遊脚軌道の実装例を見たほうが良いか

**Comment by Yusuke-Yamasaki-555** [comment]
てかそもそも、脚が届かない可能性もあるのか。ちゃんと計算していないが。

**Comment by Yusuke-Yamasaki-555** [comment]
やること
・コードの再確認、バグを出している箇所の特定。
・座標系の基準を、足裏床面から腰位置に変更してやってみる。
・歩行パターンからＩＫを解いた結果が、脚の可動範囲内にあるかの確認。

**Comment by Yusuke-Yamasaki-555** [comment]
それっぽい動歩行の動きはできた。歩行パターンは[上記](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/issues/6#issuecomment-1610920695)で示した足踏みのものを使用。

https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/7226e0f5-ccd6-4e02-a3d8-62aa54d6276e

足の軌道はちゃんとしているはず。以下は、重心位置に対する足までの距離。重心軌道はZMPに近づくように円弧を描くので、支持脚の足と重心位置までの距離が円弧に沿って縮まったりするのは正しいはず。逆に遊脚の足が重心位置から円弧に沿って離れていったりするのも正しいはず。遊脚の足が正弦波の軌道で上がっているのも確認できる。このグラフは一般的なものでは無いはずだからわかりにくいと思われる。一応記録。
![walking_no1_plot](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/3a679ac3-edf2-485f-a665-ebdac68b9c2d)

ただ、動画を見る限りキレイな足踏みにはなっていない。
* 両脚支持期間の実装ができていないから？
* 歩行パラメータが駄目だから？
* まだ足の軌道とIKがうまく適用できていない？
* 初めの0.8[s]の足の軌道がおかしいから？

10[ms]の制御周期は、WebotsのbaseTimeStepを10[ms]に設定することで適用している。今回は通信を挟んでいないので、webotsのstep()関数内で歩行パラメータを読み込んで各関節に適用しているだけなので、問題になるオーバーヘッドは存在しないはず。

**Comment by Yusuke-Yamasaki-555** [comment]
動歩行で足踏みができているっぽい。でも思ったとおりの動きにはなっていない（特に遊脚を数cm上げてほしいのに上がっていない）し転倒しちゃっているっぽいので、パラメータとか足先位置とかを確認する。


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/822628a9-a49f-4bbd-97e2-7fdeb2a0586f

**Comment by Yusuke-Yamasaki-555** [comment]
今は、歩行パターンから支持脚・遊脚の関節角度を与えるコードを書いている。が、特にX方向が上手くいっていない（集中して取り組んでいないのも原因）。
以下、X軸方向における足の位置の時間変化。0.02前に足を置くように指定しているのだが、0.03前までも足を伸ばして0.01までしか足を引いていない。式が駄目だねぇ。
コードもぐちゃぐちゃになってきたし、一旦整理し直そうか。

![Walking_log_1](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/ac19c2b8-cb44-4670-a7f4-23ac2d49bd17)

参考に、今の歩行パターン。Debug用に色んな軌道を出しているので見せられるレベルのものではないが。

![Walking_log_1-2](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/d2507313-ea61-4b2f-9338-0d5e072d3f08)

**Comment by Yusuke-Yamasaki-555** [comment]
今の歩行パラメータ。着地位置はWorld座標系で、右足裏を基準(0, 0)として設定。

{{0.0, 0.0, 0.037},  // 歩行パラメータからの着地位置(time, x, y)
  {0.8, 0.0, 0.074},  // 元は、0.037. 基準点を変えている. 
  {1.6, 0.02, 0.0}, 
  {2.4, 0.04, 0.074},  
  {3.2, 0.06, 0.0},
  {4.0, 0.08, 0.074},
  {4.8, 0.08, 0.037},
  {5.6, 0.08, 0.037}};

**Comment by Yusuke-Yamasaki-555** [comment]
X軸方向はOKかな。ただ、歩行終了時に倒れてしまうので、Y軸を修正する必要があるっぽい。

![Walking_2_fig5](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/142c95db-bc29-4a95-bf37-95923f930a73)

**Comment by Yusuke-Yamasaki-555** [comment]
んんんーーーーー


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/d8ac4f4e-0dd5-4735-bc36-8cd3f1b58553

![walking_no3_fig5](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/6ab7e145-9eae-4f62-a37f-541e3b6a82ba)

![walking_no3_fig4](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/2a0843e7-dea6-4cda-ab87-3a2e7d91308e)
![walking_no3_fig3](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/44f2ca48-ba28-46f2-bf53-b99304050a1e)
[WSC2WRH_clock.log](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/files/12171387/WSC2WRH_clock.log)

**Comment by Yusuke-Yamasaki-555** [comment]
歩行パラメータを変えてみた。X軸方向を、0.05[m]に変更。

どうもかかとを引きづっているっぽい。


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/3289e4e6-9809-4cf9-913d-af904c8b4909


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/e718ddef-8109-4a6c-bcbb-e168affd028d

**Comment by Yusuke-Yamasaki-555** [comment]
まあ、動歩行は成功してますねコレは

**Comment by Yusuke-Yamasaki-555** [comment]
遊脚の正弦波のコードがアレだったので、修正。

**Comment by Yusuke-Yamasaki-555** [comment]
うん、ここまでできればまず良いだろ。動歩行ひとまずOK、達成！

https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/01f63463-f0ee-4fb6-a705-7cb7757d9887

**Comment by yasuohayashibara** [comment]
まだちょっと足を引きずっているように見えます．
遊脚の足を上げる量を増やしてみて下さい．

**Comment by Yusuke-Yamasaki-555** [comment]
ありがとうございます。もう少し調整してみます。

**Comment by Yusuke-Yamasaki-555** [comment]
現状：

遊脚軌道：高さ0.08[m]の正弦波+0.01[m]。
両脚支持期間：0.2[s]。歩行開始時と終了時に0.1[s]の両脚支持。

足を引きずっている。特に踵が床を擦っている。コレの原因はわからん。足首Pitchに直接角度を加えるか、IKや速度指令がよろしくないのか。
あと、両脚支持をIKのときに適用しているため、歩行パターンとの乖離が多少あるのかもしれない。教科書では歩行パターン生成時に両脚支持期間を適用していたので、そこも要因か？

まずは、両脚支持期間を歩行パターン生成にちゃんと組み込むところから始めるべきか。


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/f2ffd6f8-6593-41b5-88b2-812b03acd52c

![walking_no7_fig5](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/0a26be7e-3b85-46e4-b7f8-94612d707cee)
![walking_no7_fig4](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/5b3012cf-5ca1-4604-a75c-2e823f431fde)
![walking_no7_fig3](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/f760f44d-1cfd-48e3-b903-c4d67e86969e)
[WSC2WRH_clock.log](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/files/12192575/WSC2WRH_clock.log)

**Comment by Yusuke-Yamasaki-555** [comment]
ああいや、違うか？両脚支持の適用方法を復習する。

**Comment by Yusuke-Yamasaki-555** [comment]
遊脚や両脚支持期の脚の軌道を調整してみた。ほとんど足を引きずらずに歩けるようになった。
しかし、歩行パラメータをいじると全く歩けなくなるので、やはりまだ遊脚軌道が駄目っぽい。前に指摘してもらっていた最大速度で動かすことをしていないからかも。実際、今回遊脚の初めと終わりに0.06[m]足を一瞬で上げ下げするようにしているので、実質最大速度なのだと思う。
あと、両脚支持期の時に、重心の速度・加速度の変化を滑らかにするような実装をしていないのも原因の１つかも。

以下、記録。

https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/c08d9acd-f83c-4d7d-b703-721937fa0317


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/6605c643-dd9c-4374-8e1d-4a2ccb0fcc2c


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/5498f521-18ca-42ce-8991-1ae4fe918f73

胴体中心投影点に対する脚の軌道
![walking_no8_fig6](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/b6238269-b3b4-4ef7-b85c-d85f975a6a20)
遊脚軌道
![walking_no8_fig7](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/b3d16c2a-1c0c-4f4c-9dee-51590374872b)
歩行パターン
![walking_no8_fig3](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/967c8c00-b021-416e-9590-248f0e717ef2)
胴体中心投影点に対するX軸方向の脚の軌道
![walking_no8_fig5](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/d0e982ea-cf61-491f-b442-6e5a119e66da)

**Comment by Yusuke-Yamasaki-555** [comment]
速度を最大にしてみようか。もうそれぐらいしか分からん。

**Comment by Yusuke-Yamasaki-555** [comment]
速度を最大にしてみた。遊脚軌道を、正弦波（高さ0.08[m]）に変更。まあちゃんと歩けそうなんだけど、やっぱ何故か足裏が床面と並行になっている。そのせいでつま先で床面を蹴ってしまって、歩けていないんだろうなと。コレどうしたものか。


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/66b8887c-f937-4508-8f1d-b19012b8c547

**Comment by Yusuke-Yamasaki-555** [comment]
速度を限定的に最大にしてみた。

確かにいい感じ！　足は引きずっていない。ただ、着地時のタイミングなのか、滑るときがある。

遊脚を上げ下げする、初めの0.05[s]だけ、脚各関節最大速度(12.26[m/s])を適用。


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/127809d1-71b4-4ca8-98cc-c3e62a577332

**Comment by yasuohayashibara** [comment]
歩行の目標軌道を見ると，地面から8cmまで持ち上げるようなパターンになっています．
動画を見るとそれほど足を上げていないため，おそらく逆運動学の問題のような気がします．

**Comment by Yusuke-Yamasaki-555** [comment]
ありがとうございます。確認してみます。

**Comment by Yusuke-Yamasaki-555** [comment]
足が80mmほどまで上がっていない問題、IKとFKを、直立状態のリンク状態から計算しているから説。

**Comment by Yusuke-Yamasaki-555** [comment]
そうか、既に膝を曲げて中腰っぽくなっているから、直立状態と現在の腰高さ差分をとって、差分＋足上げ高さで正弦波を計算してやる必要があるか。

**Comment by Yusuke-Yamasaki-555** [comment]
腰を基準にした
* 直立高さ：0.186 [m]
* 歩行時高さ：0.171836 [m]
* 高さ差分：0.014164 [m]

高さ差分＋足上げ高さを正弦波の振り幅に適用するので、今の振り幅0.08だと、足上げ高さは
0.08 - 0.014164 = 0.065836 [m] ~= 66 [mm]
となっているはず。

**Comment by Yusuke-Yamasaki-555** [comment]
んー、でも確かに66[mm]持ち上がっている感じでもなさそう。IKを確認します。


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/cf074021-3b54-4697-a7af-53d4cc21b2ff

**Comment by Yusuke-Yamasaki-555** [comment]
んー、逆運動学は問題なさそう。
OP2の脚構造は教科書の解析的手法の構造とほぼ一致しているので、ほぼ教科書のママ実装しているわけで。比較してみたが、特におかしな点はなかった。

ただ１点、p66一番下の姿勢の式に関しては、移行が間違っている気がしているので、そこは変更している。右辺のRx, Ryをinnverse()している。実際、教科書のママだとおかしなことになるし。

よくわからん。
足首Yaw軸から足裏面までのリンク長をIKで考えていないからか？。いや腰〜足首まででちゃんと足上げができていれば別に問題は無いはずなんだが。

たまに挙げる以下のグラフはIKから得た関節角度を元にFKを解いた結果で、ちゃんと0.08[m]の足上げができている。
![walking_no10_fig4](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/815c2ff8-b710-49f2-8a23-3a27c3234b6a)

**Comment by Yusuke-Yamasaki-555** [comment]
だから[このissueの話](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/issues/6#issuecomment-1661919998)も、間違っているのでは。正弦波の振り幅で0.08を与えていて、それを中腰状態の腰高さから引いているのだから、ちゃんと0.08[m]足を上げなきゃおかしい。

まじでよくわからん。
正しければ、膝下ぐらいまで足首関節の位置が上がっていてもおかしくないのだが。

**Comment by Yusuke-Yamasaki-555** [comment]
IKを解析的手法から数値的手法に変更してもいい（いずれそうするつもり）のだが、それしか無いかなぁ。わからん。

**Comment by yasuohayashibara** [comment]
IK -> FK で足先の位置が変化しないかを確認したほうが良いかも

**Comment by Yusuke-Yamasaki-555** [comment]
そこは確認していませんでした。ありがとうございます。確認してみます。

**Comment by Yusuke-Yamasaki-555** [comment]
IKを解く前の元の位置座標の時間変化（左図）と、IKを解いた結果を元にFKを解いて得られた位置座標の時間変化（右図）の比較。
　
変化なし。遊脚・支持脚と、右脚・左脚の比較と多少手を抜いたが、遊脚・支持脚の軌道を左右の脚にそのまま与えているので、軌道は同じになるべき。で、同じになっている。



左：支持脚・遊脚の足先位置の時間変化（歩行パターン、遊脚軌道を元に指定）
右：左脚・右脚の足先位置の時間変化（左図の値からIKを解き、その結果を元にFKした結果）

![image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/9ddccd6e-9628-4a04-9911-2129a918f4a3)


上の２図を重ねてみた。

![image](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/a8816e7a-97a6-4b19-9077-75190ca4453c)

**Comment by Yusuke-Yamasaki-555** [comment]
あ、もしかして、足上げ動作の速度を関節速度に反映していないからかコレ。
今気がついた。

今の実装だと、足上げ動作を含んだ関節角度は確かに与えているのだが、関節速度は以下の式、

各関節角速度 = ヤコビアンの逆行列 * 重心速度
（ヤコビアンは、足上げ動作を含んだ関節角度を元に計算）
（重心速度は、並進運動 x, y のみで、z方向と３軸の回転運動は０）

だと、足上げ動作が速度に考慮されていないのでは？？？

**Comment by Yusuke-Yamasaki-555** [comment]
支持脚はコレで良いんだろうけど、遊脚は駄目だろう。

遊脚軌道からどう速度を求めようか。遊脚軌道の10[ms]での値の変化量 / 0.001[s](=10[ms]) で算出できるだろうか。

**Comment by Yusuke-Yamasaki-555** [comment]
遊脚軌道の足上げ速度（= Z軸方向の測度）を以下の式で適用してみた。

絶対値| (今step遊脚軌道値[m] - 前step遊脚軌道値[m]) / 制御周期[s] | [m/s]
（制御周期 = 0.01[s]）

X, Y方向に合わせて逆ヤコビアンと掛けてやることで各関節角速度を得た。

結果、ちゃんと0.08[m]ぐらいまで足を上げるようになった。
が、次はどの値にしてもまともに歩けなくなった。足を高く上げすぎると遊脚方向への転倒動作を見せ、遊脚着地時ぐらいに床を蹴るようになった。
足上げ高さを0.02[m]ぐらいまで低くすると、今度は遊脚が床を擦る。

適用方法が悪いのか、そもそも歩行周期（今は0.8[s]（足上げ0.6[s], 両脚支持0.2[s]））などのパラメータ値が悪いのか。


* 足上げ高さ0.08[m]



* 足上げ高さ0.025[m]

**Comment by Yusuke-Yamasaki-555** [comment]
ただ、遊脚軌道の速度がそもそもおかしいかも。
遊脚軌道である正弦波の傾きの緩急と、速度変化の傾きの緩急が逆転している。傾きの傾向は同じであるべきなのに。

上：遊脚、下：遊脚のZ方向速度
![walking_no11_fig8](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/8d9e69eb-6847-4ad2-b1e6-952a512d6e00)
![walking_no11_fig9](https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/8596b0aa-f06b-4393-b562-00cc9e15b797)

**Comment by Yusuke-Yamasaki-555** [comment]
んっぁ？いや別に良いのか？速度が実際に減っていて、正弦波の頂点とほぼ一致するタイミングで最低速度なんだから、別に良いのか。

**Comment by Yusuke-Yamasaki-555** [comment]
やはりパラメータか。

**Comment by yasuohayashibara** [comment]
速度が絶対値になっている気がするのと，支持脚の時間（地面に接地している時間）が短い気がします．
むしろ支持脚の時間を長くして，両足が接地している期間（両足支持期間）を作らないと歩行を安定させるのは難しいです．

**Comment by Yusuke-Yamasaki-555** [comment]
ありがとうございます。パラメータ調整の参考にさせていただきます。

**Comment by Yusuke-Yamasaki-555** [comment]
遊脚のX軸方向の動作を修正。以下のようにパラメータ調整を行ったら以下のような歩行動作を得ることができた。
* 足上げ高さ：0.03[m]
* 歩行周期：0.8[m]（片足支持期：0.3[m]、両脚支持期：0.5[m]）
* 歩行パラメータ（右足裏中心点を基準）

| 支持脚切替タイミング | 0.0 | 0.8 | 1.6 | 2.4 | 3.2 | 4.0 | 4.8 | 5.6 |
| ------------------------------- | ----- | ---- | ---- | ---- | ----- | ---- | ----- | ---- |
| X軸方向                          | 0.0     | 0.0       | 0.02 | 0.04 | 0.06 | 0.08 | 0.08 | 0.08 |
| Y軸方向                          | 0.037 | 0.074 | 0.0 | 0.074 | 0.0 | 0.074 | 0.037 | 0.037 | 


https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/3c188b25-4094-4718-8dd9-ac53d5e3c923

若干転倒し欠けているが、床面に足裏はついていない。

パラメータ調整方法：
1. 歩行周期と両脚支持期を決め打ちする。
2. 足踏みをさせてみて、足上げ高さを転倒の有無から調整する。
3. 前進させてみる。

**Comment by Yusuke-Yamasaki-555** [comment]
歩行パラメータのZ軸方向 -> 0.03[m]、足上げ高さ -> 0.025[m]にしてみた。

https://github.com/open-rdc/ROS2_Walking_Pattern_Generator/assets/91410662/f381398c-fff5-4bc8-9346-f110670921a9

若干バランスが悪いのは、パラメータを詰めれば治るのだろうけど、それよりもソフトウェアのアーキテクチャに手を付けたほうが良さげ。

**Comment by Yusuke-Yamasaki-555** [comment]
動歩行は達成できたので、このIssueはCloseする。
以降、WPGの実装に移行する。
